server:
    port: 6005

spring:
    application:
        name: mic-orderservice
    banner:
        charset: UTF-8
    profiles:
        active: ${PROFILE}
    cache:
        type: caffeine
        caffeine:
            spec: maximumSize=500,expireAfterAccess=600s

app:
    store:
        url: ${APP_STORE_URL:http://localhost:9000}

services:
    productcategory:
        url: ${SERVICES_PRODUCTCATEGORY_URL:http://localhost:6002}
    cmsservice:
        url: ${SERVICES_CMSSERVICE_URL:http://localhost:6006}
